#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FIELD_SIZE 3

#define CELL_WH 70
#define CELL_BORDER_SIZE 5
#define CELL_FONT_SIZE 35

#define BUTTON_WIDTH 100
#define BUTTON_HEIGHT 50
#define BUTTON_BORDER_SIZE 3
#define BUTTON_FONT_SIZE 26

#define LABEL_WIDTH 175
#define LABEL_HEIGHT 50
#define LABEL_BORDER_SIZE 3
#define LABEL_FONT_SIZE 26

#define NUM_BUTTON_TARGER 1

#endif
